### ISSUE TITLE
Nested Form Fields Rendered Twice in 1.2.0 Release

### ISSUE THREAD

**Issue by macfanatic** [activeadmin/arbre#119]
After upgrading to the latest `activeadmin` and `arbre`, we realized that our nested form fields are being duplicated in our templates.

- `activeadmin 1.3.1`
- `arbre 1.2.0`
- `rails 5.2.3`
- `ruby 2.3.6`

Example form for ActiveAdmin resource:

```ruby
ActiveAdmin.register Drawer do
  form do |f|
    columns do
      column do
        panel 'Payment Methods' do
          table do
            thead do
              th 'Payment Method'
              th 'Amount Processed'
              th 'Expected on Hand'
            end

            tbody do
              f.semantic_fields_for :payments do |payments|
                tr(class: cycle('odd', '')) do
                  td(class: 'hidden') { payments.input :id, as: :hidden }
                  td { payments.object.payment_method.name }
                  td { payments.object.amount_processed.format }
                  td { payments.object.amount_expected_on_hand.format }
                end
              end
            end
          end
        end
      end
    end
  end
end
```

We end up with the `semantic_fields_for` rendering double the amount of rows, a whole group and then the entire collection again a second time.

Leaving `activeadmin` and `rails` locked to the versions mentioned above, but downgrading to `arbre` version `1.1.1` (the previous release) fixes the issue.

**Comment by deivid-rodriguez** [comment]
Thansk for the report, I'll have a look :+1:

**Comment by timoschilling** [comment]
How does it look with `arbre 1.1.1`?

**Comment by deivid-rodriguez** [comment]
What about activeadmin `2.0.0.rc1`? Does it work there? Also, can you provide a sample application reproducing the regression?

**Comment by macfanatic** [comment]
The issue exists in all the following configurations:

* `arbre 1.2.0.rc1` and `activeadmin 1.3.1`
* `arbre 1.2.0` and `activeadmin 1.3.1`
* `arbre 1.2.0` and `activeadmin 2.0.0.rc1`

The issue does not exist with:

* `arbre 1.1.1` and `activeadmin 1.3.1`
* `arbre 1.1.1` and `activeadmin 2.0.0.rc`

It very much appears to have been introduced and present in both the arbre RC1 and final versions.

I'll see if I can get a demo repo setup and shared to reproduce.

**Comment by macfanatic** [comment]
Here is a link to a reproduction repo, the `README` includes setup and what to do for viewing the issue.

https://github.com/madebylotus/arbre-regression-1.2.0-example

**Comment by deivid-rodriguez** [comment]
Nice, thanks so much @macfanatic!

**Comment by deivid-rodriguez** [comment]
Run a bisection over you app and the culprit seems https://github.com/activeadmin/arbre/pull/64.

**Comment by seanlinsley** [comment]
Here's another example where double rendering happens: one form accidentally included `f.actions` inside of `f.inputs`, leading to the submit and cancel buttons to be double-rendered. It was easy enough to fix by moving it out of the `inputs` block.

```ruby
  form do |f|
    f.inputs do
      # ...

      f.actions
    end
  end
```
<img width="287" alt="Screen Shot 2019-04-11 at 10 14 32 AM" src="https://user-images.githubusercontent.com/688886/55969464-73fc7580-5c43-11e9-9074-8b24786574c2.png">

**Comment by deivid-rodriguez** [comment]
I worked a bit on this today in this [branch](https://github.com/activeadmin/arbre/compare/regression?expand=1).

It sounds like regardless of how we end up fixing #46, we should probably revert #64.

**Comment by varyonic** [comment]
madebylotus/arbre-regression-1.2.0-example#1
