### ISSUE TITLE
Ruby 2.7 support

### ISSUE THREAD

**Issue by mirelon** [activeadmin/arbre#167]
I see the branch https://github.com/activeadmin/arbre/tree/ruby27_warnings
to suppress ruby 2.7 warnings,
but isn't it worth adding support for ruby 2.7 (and following 3.0?)

By adding a new syntax
`helpers.send(...)` instead of `helpers.send(name, *args, &block)` here: https://github.com/activeadmin/arbre/blob/master/lib/arbre/element.rb#L181

Is a branch for 2.7 a good idea? Because it won't be compatible with 2.6...

**Comment by deivid-rodriguez** [comment]
I've seen warnings in that same place but I wasn't planning to use a ruby 2.7 specific syntax to fix it. I think it can be fixed in a backwards compatible way.

Other than that warning, `arbre` works fine on ruby 2.7, right?

**Comment by mirelon** [comment]
Yeah, it works, fine. I agree with backward-compatible (probably with ruby2_keywords gem: https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/#a-compatible-delegation)

**Comment by deivid-rodriguez** [comment]
Yeah, `ruby2_keywords` could be an option, but it looks really ugly to me, honestly.

I think I would prefer a more verbose and less DRY alternative like:

```
if RUBY_VERSION >= "2.7"
  # current code adapted to keyword separation
else
  # current code
end
```

If that would work.
