### ISSUE TITLE
Time for a release?

### ISSUE THREAD

**Issue by utkarsh2102** [activeadmin/arbre#173]
Hi,

There have been 57 commits so far since the last release, perhaps time for another one?

**Comment by deivid-rodriguez** [comment]
Hi! Is there any specific change you're looking for? I don't think we have many user facing changes unreleased.

**Comment by utkarsh2102** [comment]
Hi,
Thanks to @dependabot-bot, there have been bumps in the dependencies (which match the ones in the Debian archive), so I just wanted to sync things. But no rush, whatsoever :)

**Comment by deivid-rodriguez** [comment]
Yeah, but only development dependencies, so no changes affecting end users of the gem. So, I think we can get until there's something new that we can give to our users.

**Comment by utkarsh2102** [comment]
Indeed, no rush as far as everything works ;)
