### ISSUE TITLE
Release for Ruby 2.7 deprecation warnings?

### ISSUE THREAD

**Issue by mauro-oto** [activeadmin/arbre#223]
I just saw https://github.com/activeadmin/arbre/issues/173 and https://github.com/activeadmin/arbre/issues/167 around Ruby 2.7 warnings were closed earlier this year. 

Could you please consider releasing a 1.3.0 version using the `ruby2_keywords` gem brought in by https://github.com/activeadmin/arbre/commit/b546d7a10b95001cb7bd1273bbaa55172de77e98 so that we get less warnings coming from this gem for the Ruby 2.7 upgrade?

Thank you!!! 🙏 

cc @deivid-rodriguez

**Comment by deivid-rodriguez** [comment]
Hi @mauro-oto! Yes, I'll do this soon!
