### ISSUE TITLE
Template tag?

### ISSUE THREAD

**Issue by MatheusRich** [activeadmin/arbre#252]
I was wondering if arbre supports the [template tag.](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template) 

As far as I understood, this tag is missing here:

https://github.com/activeadmin/arbre/blob/348763dfd5cc2ab220b7a8121319b21919ad7886/lib/arbre/html/html5_elements.rb#L4-L14

Can we add it?

**Comment by javierjulio** [comment]
I would accept a PR for this if you still want to contribute that change.
