### ISSUE TITLE
Override `p`

### ISSUE THREAD

**Issue by seanlinsley** [activeadmin/arbre#53]
Arbre uses `para` for `<p>` tags because `p` is a Ruby method, similar to `puts`. I understand the unwillingness to override Ruby methods, but I think it's less surprising than requiring people to read the Arbre documentation in order to create paragraph tags.

I propose that we release a final version for 1.x (1.99) that:
- warns that behavior will change for `p`
- deprecates `para`

As well, that we immediately release a 2.0 version with the method renamed from `para` to `p`.

**Comment by timoschilling** [comment]
:+1:
