### ISSUE TITLE
Adding inline javascript to form?

### ISSUE THREAD

**Issue by adamaiken89** [activeadmin/arbre#61]
Thank you for creating such useful tool.
I would like to know how can we add inline javascript to form?

**Comment by timoschilling** [comment]
What do you mean?
```html
<form onsubmit="alert()">...</form>
```
or
```html
<form ...>
  <script>...</script>
</form>
```

**Comment by Aiken00** [comment]
Thank you for your reply.

I would like to achieve the second one. 

```
<form ...>
  <script>...</script>
</form>
```

**Comment by TJamesCorcoran** [comment]
I have a very similar question: is there any way to add 

<script>
   arbitrary javascript
</script>

to a .html.arb file?

**Comment by b264** [comment]
This might do that
```
text_node ('<script>' + arbitrary_javascript + '</script>').html_safe
```
of course this comes with the warnings that you probably shouldn't be doing that at all!  Why not link a separate file?
```
text_node '<script src="/static/assets/javascripts/foobar.js?cache_version=0"></script>'.html_safe
```

**Comment by varyonic** [comment]
I'm guessing using the script tag in Arbre doesn't render correctly?  `script { ... }`  If so perhaps that is a bug.

**Comment by roberthopman** [comment]
perhaps: https://github.com/activeadmin/activeadmin/issues/340

**Comment by varyonic** [comment]
Specifically https://github.com/activeadmin/activeadmin/issues/340#issuecomment-340891891 suggests that `script { raw "..." }` should work.

**Comment by roberthopman** [comment]
I can confirm it works.
