### ISSUE TITLE
New minor/patch release?

### ISSUE THREAD

**Issue by tagliala** [activeadmin/arbre#619]
Hello, is it possible to have a minor/patch release to include performance of #617?

**Comment by javierjulio** [comment]
@tagliala yes you are welcome to cut a release for that change. I don't believe we have any other user facing changes here so I think that would be a new patch release. You should be able to do that. Can you please try it and let me know if you have any issues? Thanks!

**Comment by tagliala** [comment]
Reopening as reminder
