### ISSUE TITLE
AS 3.0 is probably not supported anymore

### ISSUE THREAD

**Issue by tagliala** [activeadmin/arbre#621]
https://github.com/activeadmin/arbre/blob/2a75591fc5646b8eaffbcf875a8c06b476022f04/arbre.gemspec#L26C3-L26C48

The minimum required Ruby version is 2.7, I don't know if this supports AS 3.0

https://github.com/activeadmin/arbre/blob/2a75591fc5646b8eaffbcf875a8c06b476022f04/arbre.gemspec#L24

Probably this can't be done in a patch release, but I'm asking what the minimum supported version should be

**Comment by javierjulio** [comment]
For ActiveSupport v3, I'm not sure if it would matter since we've had that minimum required version set for a few years now. I don't have an issue with bumping that to Ruby 3.0 minimum either. I don't think that should block a patch release though.

**Comment by tagliala** [comment]
Closing here for the moment
