### ISSUE TITLE
Force encoding (Incompatible character encodings: UTF-8 and Windows-1251)

### ISSUE THREAD

**Issue by deff7** [activeadmin/arbre#68]
Hello! When I try to output collection of elements with inconsistent encodings, I got the exception:

> incompatible character encodings: UTF-8 and Windows-1251

Cause of the exception is  https://github.com/activeadmin/arbre/blob/a3349fb4a48e700194db56bd1b520b85e1ac844b/lib/arbre/element_collection.rb#L18-L23

Is forcing of encoding in **to_s** method for all elements of collection before join is good idea? Or I should solve this problem in my application?

**Comment by varyonic** [comment]
You should `encode("UTF-8", "Windows-1252")` in your app.

**Comment by deff7** [comment]
Ok, thanks
