### ISSUE TITLE
Document usage of .arb files

### ISSUE THREAD

**Issue by dkniffin** [activeadmin/arbre#69]
I just stumbled upon this awesome feature. I didn't realize you could create template files with `.arb` extension, and it would set up the Arbre context. This should be added to the documentation.

**Comment by varyonic** [comment]
Yes, please. See also [this question on SO](https://stackoverflow.com/questions/31747483/how-to-use-arbre-gem-in-rails)  A similar project with extensive documentation is (was?) [Erector](http://erector.github.io/erector/rails.html)

**Comment by varyonic** [comment]
See #70
