### ISSUE TITLE
Spec Tests using to_be_success predicate are being deprecated

### ISSUE THREAD

**Issue by imacubsfan23** [activeadmin/arbre#74]
I'm new here, and looking for a way to contribute to this seemingly useful gem.

I noticed after forking the repo that rspec is deprecating "to_be_success" in rails 6.0, and I would like to change it to its updated version of "to_be_successful"

**Comment by varyonic** [comment]
Thanks @imacubsfan23 Arbre is relatively stable but it would be really nice to have some performance benchmarks to compare with Slim, Hamlit, Fortitude, etc. if that appeals to you.
